### ISSUE TITLE
fragment間での往復について

### ISSUE THREAD

**Issue by zzztuzzz** [zzztuzzz/MaterialGreat2#5]
activityが一枚しかなく、
処理のほとんどをfragmentに任せています。

特に、第二階層の構成で、

メッセージングと、ユーザーデータ詳細が往復が可能な作りになる。
が、fragment使う際に、inflater使っている分、使い回せるからメモリは心配しなくて大丈夫ですか？

**Comment by ichigotake** [comment]
👀

**Comment by ichigotake** [comment]
ActivityとFragmentの数が 1:n になっていると画面遷移やActivityの実装が複雑になりやすく、Intentによる連携やアプリ内での使い回しなどのあらゆる面で再利用が難しくなります.

基本的に1画面1Activityとして作っていく事が望ましいです. 

NavigationDrawerをタップした際の挙動は Fragment を replace していく実装で良いと思いますが、それ以外は1画面1Activityがベターです.

Activityを利用する代表的なメリットはIntentとAndroidManifestでしょう.  画面ごとにactivityの定義を用意する事で、画面に応じて回転やキーボード等のUIの制御が出来ます.

さらに、intnet-filterの定義が画面ごとに分かれているので、「共有」を受けた際の遷移先の振り分けが不要になります.1つのActivityでやろうとすると、Activity内で起動する画面を振り分けたりする必要が出てきます.

どんな場合でも1画面1Activityが良い言いませんが、慣れないうちは1画面1Activityを指針としてやっていくと良いでしょう. Fragment は画面分割の道具として捉えると理解しやすいかもしれません.

**Comment by ichigotake** [comment]
> メモリは心配しなくて大丈夫ですか？

Fragment内でよほど悪いコードを書いていない限りは大丈夫です.

それよりも、1 Activityで管理するFragmentが多くなりすぎる事による保守性の低下の方が心配です.

**Comment by zzztuzzz** [comment]
これはクリティカルですね汗

すぐに1activity,1画面に変更するように訂正したいと思います。

> NavigationDrawerのある画面は Fragment を replace していく実装で良いと思いますが、それ以外の画面繊維は1画面1Activityがベターです.

ここはfragmentでいい流れ承知しました。
第一階層はfragmentの切り替えで対処、

第二階層、
第三階層
以降はactivityで一画面事に作成していきたいと思います
